make testing faster

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,21 +40,21 @@ jobs:
           pip install pylint pylint-airflow
           pip install -r requirements.txt
           pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
-      - name: setup airflow and run list_dags
-        run: |
-          export AIRFLOW__CORE__LOAD_EXAMPLES="False"
-          export AIRFLOW__CORE__PLUGINS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/plugins"
-          export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/dags"
-          airflow initdb
-          airflow info
-          airflow list_dags
-          # check if list_dags has error if yes exit CI
-          daglist=`airflow list_dags`
-          errorstring="Error"
-          if [[ $daglist == *"$errorstring"* ]]; then
-              echo "error in dags"
-              exit 1
-          fi
+      # - name: setup airflow and run list_dags
+      #   run: |
+      #     export AIRFLOW__CORE__LOAD_EXAMPLES="False"
+      #     export AIRFLOW__CORE__PLUGINS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/plugins"
+      #     export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/dags"
+      #     airflow initdb
+      #     airflow info
+      #     airflow list_dags
+      #     # check if list_dags has error if yes exit CI
+      #     daglist=`airflow list_dags`
+      #     errorstring="Error"
+      #     if [[ $daglist == *"$errorstring"* ]]; then
+      #         echo "error in dags"
+      #         exit 1
+      #     fi
       - name: test web readiness
         run: |
           ls -la /usr/bin/
