align workflow to dea-australia

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,10 +30,29 @@ jobs:
           update-conda: true
           python-version: ${{ matrix.python-version }}
           conda-channels: anaconda, conda-forge
-      - run: conda --version
-      - run: which python
-      - run: |
-          pip install apache-airflow[aws,kubernetes,postgres,redis,ssh,celery]==1.10.11
-          pip install -r requirements.txt
+      - name: Check conda version
+        run: conda --version
+      - name: Check python
+        run: which python
+      - name: Install airflow and run pylint
+        run: |
+          pip install apache-airflow[aws,kubernetes,postgres,redis,ssh,celery]==1.10.14
           pip install pylint pylint-airflow
-          PYTHONPATH=plugins pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
+          pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
+      - name: setup airflow and run list_dags
+        run: |
+          export AIRFLOW__CORE__LOAD_EXAMPLES="False"
+          export AIRFLOW__CORE__PLUGINS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/plugins"
+          export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/dags"
+          airflow initdb
+          airflow connections --add --conn_id aws_nci_db_backup --conn_type aws --conn_login AWSKEY --conn_password AWS_PASS
+          airflow connections --add --conn_id lpgs_gadi --conn_type ssh --conn_login USERNAME --conn_password PASS
+          airflow info
+          airflow list_dags
+          # check if list_dags has error if yes exit CI
+          daglist=`airflow list_dags`
+          errorstring="Error"
+          if [[ $daglist == *"$errorstring"* ]]; then
+              echo "error in dags"
+              exit 1
+          fi
