test k8s

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,36 +34,24 @@ jobs:
         run: conda --version
       - name: Check python
         run: which python
-      # - name: Install airflow and run pylint
-      #   run: |
-      #     pip install apache-airflow[aws,kubernetes,postgres,redis,ssh,celery]==1.10.14
-      #     pip install pylint pylint-airflow
-      #     pip install -r requirements.txt
-      #     pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
-      # - name: setup airflow and run list_dags
-      #   run: |
-      #     export AIRFLOW__CORE__LOAD_EXAMPLES="False"
-      #     export AIRFLOW__CORE__PLUGINS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/plugins"
-      #     export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/dags"
-      #     airflow initdb
-      #     airflow info
-      #     airflow list_dags
-      #     # check if list_dags has error if yes exit CI
-      #     daglist=`airflow list_dags`
-      #     errorstring="Error"
-      #     if [[ $daglist == *"$errorstring"* ]]; then
-      #         echo "error in dags"
-      #         exit 1
-      #     fi
-      - name: test web readiness
+      - name: Install airflow and run pylint
         run: |
-          sudo apt-get install dumb-init
-          /usr/bin/dumb-init -- bash -c > true \
-            && mkdir -p /home/airflow/.local/bin \
-            && export PATH="/home/airflow/.local/bin:$PATH" \
-            && echo "*** installing requirements..." \
-            && /home/airflow/scripts/install-requirements.sh \
-            && echo "*** installing extra pip packages..." \
-            && pip install --user  "authlib"  "Flask-AppBuilder==3.1.1"  \
-            && echo "*** running webserver..." \
-            && exec airflow webserver
+          pip install apache-airflow[aws,kubernetes,postgres,redis,ssh,celery]==1.10.14
+          pip install pylint pylint-airflow
+          pip install -r requirements.txt
+          pylint --load-plugins=pylint_airflow --disable=C,W --disable=similarities dags
+      - name: setup airflow and run list_dags
+        run: |
+          export AIRFLOW__CORE__LOAD_EXAMPLES="False"
+          export AIRFLOW__CORE__PLUGINS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/plugins"
+          export AIRFLOW__CORE__DAGS_FOLDER="/home/runner/work/deafrica-airflow/deafrica-airflow/dags"
+          airflow initdb
+          airflow info
+          airflow list_dags
+          # check if list_dags has error if yes exit CI
+          daglist=`airflow list_dags`
+          errorstring="Error"
+          if [[ $daglist == *"$errorstring"* ]]; then
+              echo "error in dags"
+              exit 1
+          fi
